apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: stroodle
  namespace: argocd
spec:
  clusterResourceWhitelist: []
  description: stroodle project
  destinations:
    - namespace: "stroodle"
      server: "https://kubernetes.default.svc"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: stroodle
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "-1"
