apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: infra
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: k0s-prod/argocd/_namespaces
    repoURL: https://github.com/kaplan-michael/k8s-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

