apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k0s-prod/argocd/rook-ceph
    repoURL: https://github.com/kaplan-michael/k8s-infra.git
    targetRevision: HEAD


