apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kissj-staging
  namespace: kissj-staging
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.8
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: kissj-staging
      owner: kissj
  postgresql:
    parameters:
      timezone: "Europe/Prague"
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: kissj-backup-s3
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: kissj-backup-s3
  namespace: kissj-staging
spec:
  configuration:
    destinationPath: s3://kissj-db-backup/staging/hprod01
    endpointURL: https://s3.eu-central-1.amazonaws.com
    s3Credentials:
      accessKeyId:
        name: aws-credentials
        key: accesskey
      secretAccessKey:
        name: aws-credentials
        key: secretkey
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: kissj-staging-backup
  namespace: kissj-staging
spec:
  backupOwnerReference: self
  cluster:
    name: kissj-staging
  immediate: true
  method: plugin
  schedule: 0 0 0 * * *
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
