apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
  name: kissj-staging-dragonfly
  namespace: kissj-staging
spec:
  authentication:
    passwordFromSecret:
      key: password
      name: kissj-staging-dragonfly
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
