apiVersion: apps/v1
kind: Deployment
metadata:
  name: logto
  labels:
    app.kubernetes.io/name: logto
    app.kubernetes.io/instance: logto
spec:
  replicas: 1
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: logto
      app.kubernetes.io/instance: logto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: logto
        app.kubernetes.io/instance: logto
    spec:
      initContainers:
        - name: db-wait
          image: busybox:latest
          command: ['sh', '-c', 'until nc -z ${PGHOST} ${PGPORT}; do echo waiting for database; sleep 2; done;']
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: logto-app
                  key: host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: logto-app
                  key: port

        - image: ghcr.io/logto-io/logto:1.25.0
          name: init-connectors
          env:
            - name: CI
              value: 'true'
          command:
            - /bin/sh
          args:
            - '-c'
            - 'npm run cli connector add -- --official'
          volumeMounts:
            - name: connectors
              mountPath: /etc/logto/packages/core/connectors
      containers:
        - name: logto
          image: ghcr.io/logto-io/logto:1.25.0
          imagePullPolicy: IfNotPresent
          env:
            # DB configuration
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: logto-app

            # Logto configuration
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3001"
            - name: ADMIN_PORT
              value: "3002"
            - name: ENDPOINT
              value: "https://auth.kpml.net"
            - name: ADMIN_ENDPOINT
              value: "https://admin.auth.kpml.net"
            - name: ADMIN_DISABLE_LOCALHOST
              value: "0"
            - name: TRUST_PROXY_HEADER
              value: "1"
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
            - name: admin
              containerPort: 3002
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /api/status
          #    port: http
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          #readinessProbe:
          #  httpGet:
          #    path: /api/status
          #    port: http
          #  initialDelaySeconds: 10
          #  periodSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: connectors
              mountPath: /etc/logto/packages/core/connectors
      volumes:
        - name: connectors
          persistentVolumeClaim:
            claimName: logto-connectors