apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logto-connectors
  labels:
    app.kubernetes.io/name: logto
    app.kubernetes.io/instance: logto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi