apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kissj-production-postgresql
  namespace: kissj-production
spec:
  encryptedData:
    admin-password: AgAi4X/bFl+FInfDP9I32zrJtEOlYtPO843CyC2ll8YQRhDBJno6h8l7IuCW6xtBH6oVZUcUUndISAjQFxlZJuCVZ7DQy7McLcDHjGtsru6jAJxagiJIJjRV18cUH/yTC7Jl6viD5Ardr41/5+LRphSIhTOUO4QMzcxAXo5gr1GbjNfCFyaVi1g5kzXHtP50F5SZzJM/G43U8UUX4OTtdd/dmnOFPQADOb2OxpZ4O2KGG3yAlZs3OZW8o58HlSrlvmuV+C/1cnsSIVQPH9kcm82cOQMcGLum63FAki/7B4ZpxemoOBombOnMVCS+04dmSb501Ctis28QARk4IbM7xUdtnMF4PPbxE4bABgzhWGR2LOMlC+Lbg8xSCAS2qMsdvnkuXaNzrTcom1nl82gry+Tw/0vMgq0G37BuEczLN6ERb7wr9lC/jQtuEN+gYiQPxoGI8WZCMfN687qykf5R3rVLr/T5r8zFrUAAI174+Ix7RrSYRaEuub793/usOccTe7OBZlxcaefmzgQj9HB69h4tkC0PgyvaWH/DCBgRrYwjJ2/Vvdlow9Y/vEq5NZIL6MH4JcmOy4YEJqj3NEoKU3js1wD8fTZWHgnZ4eSXs4Uq7ZjjFmqgkFBcQ7zTORHg00DyOabuIHhFTk5t4oFMJ3lLlCyVsKqqHDz5k1uE/3HSKuJ+vLK5srC8WJALzeJbRdCMlLwWmMtaRNo1N5hooFUl6v8=
    user-password: AgAWJh4fdqRDfRNLsESBmdxLoA9zypfbynhlk8AA9uLLX47GnO5RpMRUzRqruFbMgrjiU/q3h8ReHMRAaV+3l4yRnsiORBoecVoSHGBdQGSCQAG4tb3uPgzTtGaiqEBJ0+vYPUg76k99xETGcfOsRue8wYTkIFdiJF6prLZ/1dhhK+zTGIp1JdOkudE55bf62A3T/wOHShXMofNLe+PTUOjOIgar1t7lobou/3oU7qrlqo6S2hH1DnoenxxC0UCuYhedjaM6lj/n7AR73XFeJv4dJzp8o9H+Xv34b0HrywqoEUH/MEU5pZi2lJy/+sFidzOIx6Sm0T0iklZS/1caVoI76gZ5P7kUPdTkm2RONL7OX+sCEtD216h+K1LlfCOqPktXMuEIKKxxbiEGwOo3EzQOcFqkqQQsYPMA0bulYCJGFsE3z+axsv2fI5oifcD//XAFF4NZh5wndbya6xT+TkGF9jn3gZAXiV2T4z+DGKn6lLKxCRFztOZIHyjjwjNpZlna/T/mnkdpOMN/5ojMdN4aZiJ32DKTlWe8GoXOt5J44vV85XzbOl5hCqdEcsJD4VaHiZr6osjO3VUsIC+pyqYJTd/GtgC2Hdz/Ynh/9aQcJ3YBedj6aR4R1n5tn86owD48lNeJCuD438Yxj/MW/CqHtD0FhLONZ6mTkZC7gE6r8FzpYW5JV7SvApwAgXxwQx/C56wERO+X7Qz0V4wLkwDbhtY=
  template:
    metadata:
      creationTimestamp: null
      name: kissj-production-postgresql
      namespace: kissj-production
    type: Opaque

