postgresql:
  global:
    storageClass: mayastor-3

    postgresql:
      auth:
        username: kissj
        existingSecret: kissj-production-postgresql
        secretKeys:
          adminPasswordKey: "admin-password"
          userPasswordKey: "user-password"
          
        database: kissj-production

  primary:
    persistence:
      enabled: true
      size: 10Gi

    extendedConfiguration: |-
      huge_pages = off

    extraVolumeMounts:
      - name: pg-sample-config
        mountPath: /opt/bitnami/postgresql/share/postgresql.conf.sample
        subPath: postgresql.conf.sample
    extraVolumes:
      - configMap:
          name: pg-sample-config
        name:  pg-sample-config
  extraDeploy:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: pg-sample-config
      data:
        postgresql.conf.sample: |-
          huge_pages = off


tergum-cronjob:
  schedule: "0 0 * * *"
  extraName: tergum-postgres-backup
  tergumConfig:
      Meta:
        SchemaVersion: 3
      Telemetry:
        CollectBackupLog: true
        CollectHostData: true
      Notification:
        Targets:
          - SlackWebhook:
              SendOK: true
              URLs:
                - $SLACK_WEBHOOK_URL

      Backups:
        - ID: kissj-production
          Source:
            Postgres:
              Host: $POSTGRES_HOST
              Port: 5432
              User: $POSTGRES_USER
              Password: $POSTGRES_PASSWORD
              Database: $POSTGRES_DB
          Targets:
            - ID: kissj-db-backup
              Middlewares:
                - Gzip: {}
              S3:
                AccessKey: $S3_KEY
                SecretKey: $S3_SECRET
                Region: $S3_REGION
                BucketName: $S3_BUCKET
                Prefix: production
                Suffix: sql.gz
              
  # Optional
  image: ghcr.io/tergum-extra/postgres-with-tergum:14-tergum-v0.31.1
  useV2: true
  mountRootPath: false  
  existingSecret: kissj-production-postgresql-backup
  expandEnv: true