apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kissj-staging-postgresql
  namespace: kissj-staging
spec:
  encryptedData:
    admin-password: AgCFINbWvO8Vw/1fTs9C8ZiK6yzQa/GJCIQkSOTHukaVDD23FnoDaOXj3MoUeZbEMsesBurhZEpEQrtZeeMacavkuT5pJPB1ZbBv9LXNqD3PM9+jrxgeSGMfP5Bb9oAfdZg2uj5Q0/44Ay/2Rn/uxujjGb8iy8QgdhqYvHhaNhou8jDdaSkI52Qnwh5HUfsCiH9s5yq9bkVBOSTmwYHSYlbT/ifdqnoDST2Z1mNm5vlgMMcoLoXLZwOCAYgOyxyk4sxjs9CoqhJNMLDr3dHlrbEenatUxtAQB2gl/JL5JljkEAwnS78Cchavb3FnzoBFG6cImY6UZZZkg/TDuDd1eub6ZYTG1DRXfi7/0N15CuGvxGl82Usm4CUxuHwHOcugZAinn25WbSdd/vsqmv93bqcGUzXx/34JIw6M/Bu7+/OeAh0srmktRyOn5ACMfvff4bwrxLR/ZH4YF9Iz+9hk0fhYe3Ig370mxr9klLo6Yb/qYRpCBEMoPt7iyakAZQky5U3OoPxMzkUCSnEGy6ytRuBIELBomDpK0rrKkdNBr+2SS9WCsNOlQG5Ka0AfblyArWld/AewWpl0+98pFygD6cfq1e/mY65Bg/DDtElbx9vAbQVClrVbM18+HBHGO6jKHMa6x+TA7uliS85As231KU/gxsdynyAbaQwKZN5symjHO1PvEFNhvBhxoQNArNQuMi9uQ2A9w/FGBfsTcXmFRLXzbmk=
    user-password: AgBlrMdz+rX2kku9ZjCFuWprTyHD2ceQpWXhIP4002sAaSzqKscz0/sSoYxC80gnLA7YhZsNDUN+ND/smCrCbs8NBu+RIWdPlWjrez/XfAH5Izd4IcPZil8RA0wuxlSW77rwV2LFWaUQmNqMCIripxxRN9awPVCGx0RBg+roBbi26yvSVfzNDoIxijrVonUKDDFiulCMeA6iYLQSx+cpnjTTD0keU1CJ5PeSQuhBUx/8o1yER6eg5GSFCEfu5AStwX/CYQ5tvQa1h9tGxiDlnYax+dfz8JzibKqP8Zkh1fkCOKyHOfT6vqDSvRMZxnZM91eCwPcf/FtTITzeY10oQeeS8x/WP8l929F4XarUmV2wXhBeoTdBT3MfZGGAU8mybzpA2UQ3UjdPBU9SRk2w4g2KDEPMEzi+Jxc9cghKgDDrd7jUVfLAc2XOe0FswNPWWEA4IHB/labcJEkgHw5HzGwkSwYFZwcWYuDiVQeZO3TPJu2EoSnuiqF8goTwZEoXQm6Ds3x32XB5gmMfm8WrnVIC078PHHX+AARN8ZWcH84TZPTo0jeUdKEajAmEEkzcU5dXSUZZ/92OoBabXEf79kS0iw9GeWf/ACxY/3iUMytSup3T3qnGJeUfZ4mmJMxA4JBrwh7/BsDdEzp7mttjp2xg50A+Myg0sSs1NqPgW76gmXxD0qyEgMBfh80yZ6wRIEyMkXrK5X0/5778Lv+d9qJcxSc=
  template:
    metadata:
      creationTimestamp: null
      name: kissj-staging-postgresql
      namespace: kissj-staging
    type: Opaque

