postgresql:
  image:
    debug: true
  global:
    storageClass: mayastor-3
    postgresql:
      auth:
        username: kissj
        existingSecret: kissj-staging-postgresql
        secretKeys:
          adminPasswordKey: "admin-password"
          userPasswordKey: "user-password"
          
        database: kissj-staging

  primary:
    persistence:
      enabled: true
      size: 10Gi
    
    extendedConfiguration: |-
      huge_pages = off


tergum-cronjob:
  schedule: "0 0 * * 0"
  extraName: tergum-postgres-backup
  tergumConfig:
      Meta:
        SchemaVersion: 3
      Telemetry:
        CollectBackupLog: true
        CollectHostData: true
      Notification:
        Targets:
          - SlackWebhook:
              SendOK: true
              URLs:
                - $SLACK_WEBHOOK_URL

      Backups:
        - ID: kissj-staging
          Source:
            Postgres:
              Host: $POSTGRES_HOST
              Port: 5432
              User: $POSTGRES_USER
              Password: $POSTGRES_PASSWORD
              Database: $POSTGRES_DB

          Targets:
            - ID: kissj-db-backup
              Middlewares:
                - Gzip: {}
              S3:
                AccessKey: $S3_KEY
                SecretKey: $S3_SECRET
                Region: $S3_REGION
                BucketName: $S3_BUCKET
                Prefix: staging
                Suffix: sql.gz
              
  # Optional
  image: ghcr.io/tergum-extra/postgres-with-tergum:14-tergum-v0.31.1
  useV2: true
  mountRootPath: false  
  existingSecret: kissj-staging-postgresql-backup
  expandEnv: true