apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infowars
  namespace: argocd
spec:
  destination:
    namespace: infowars
    server: https://kubernetes.default.svc
  project: infowars
  source:
    repoURL: https://gitlab.com/horskto2/InfoWars.git
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
