apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kaplan-web
  namespace: argocd
spec:
  destination:
    namespace: kaplan-web
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kaplan-michael/website
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: kaplan-web
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "-1"
