apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: argocd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kaplan-michael/k8s-infra
    targetRevision: HEAD
    path: manifests/policies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
