apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: zitadel-prereqs
  name: zitadel-prereqs
  namespace: argocd
spec:
  destination:
    namespace: zitadel
    server: https://kubernetes.default.svc
  project: zitadel
  sources:
    - repoURL: https://github.com/kaplan-michael/k8s-infra.git
      path: manifests/zitadel
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
