apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-external-dns-hostnames-skauti-uragan-zbraslav
  annotations:
    policies.kyverno.io/title: Restrict External DNS Hostnames
    policies.kyverno.io/description: >
      Enforce that any Service must have an external-dns hostname
      annotation that is either exactly "skauti-uragan-zbraslav.cz" or a subdomain ending with ".skauti-uragan-zbraslav.cz".
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: validate-dns-annotation-stroodle
      match:
        resources:
          namespaces:
            - stroodle
            - infowars
          kinds:
            - Service
            - Ingress
          annotations:
            external-dns.alpha.kubernetes.io/hostname: "*"
      validate:
        message: "Hostname must be exactly 'skauti-uragan-zbraslav.cz' or a subdomain ending with '.skauti-uragan-zbraslav.cz'."
        anyPattern:
          - metadata:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: "skauti-uragan-zbraslav.cz"
          - metadata:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: "*.skauti-uragan-zbraslav.cz"
