---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ghc-cutoffs-service-user
  namespace: ghc-cutoffs
---
apiVersion: v1
kind: Secret
metadata:
  name: ghc-cutoffs-service-user-token
  namespace: ghc-cutoffs
  annotations:
    kubernetes.io/service-account.name: ghc-cutoffs-service-user
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ghc-cutoffs-role
  namespace: ghc-cutoffs
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ghc-cutoffs-role-binding
  namespace: ghc-cutoffs
subjects:
  - kind: ServiceAccount
    name: ghc-cutoffs-service-user
    namespace: ghc-cutoffs
roleRef:
  kind: Role
  name: ghc-cutoffs-role
  apiGroup: rbac.authorization.k8s.io
