---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kissj-staging-service-user
  namespace: kissj-staging
---
apiVersion: v1
kind: Secret
metadata:
  name: kissj-staging-service-user-token
  namespace: kissj-staging
  annotations:
    kubernetes.io/service-account.name: kissj-staging-service-user
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kissj-staging-role
  namespace: kissj-staging
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kissj-staging-role-binding
  namespace: kissj-staging
subjects:
  - kind: ServiceAccount
    name: kissj-staging-service-user
    namespace: kissj-staging
roleRef:
  kind: Role
  name: kissj-staging-role
  apiGroup: rbac.authorization.k8s.io
